# Generated by Django 3.0.6 on 2020-06-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200603_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='major',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
