# Generated by Django 3.0.6 on 2020-06-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltor',
            name='date_teaming',
        ),
        migrations.AlterField(
            model_name='skilltor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
