# Generated by Django 3.0.6 on 2020-06-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('chat', models.CharField(blank=True, max_length=50)),
                ('linkedin', models.CharField(blank=True, max_length=50)),
                ('about', models.CharField(blank=True, max_length=50)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('major', models.CharField(blank=True, choices=[('a', 'FEB'), ('b', 'FIB'), ('c', 'FMIPA'), ('d', 'FISIPOL'), ('e', 'FT')], max_length=50)),
                ('skill', models.CharField(blank=True, choices=[('a', 'Hacker'), ('b', 'Hustler'), ('c', 'Hipster')], max_length=50)),
                ('topics', models.CharField(blank=True, choices=[('a', 'software engineering'), ('b', 'UI UX ')], max_length=50)),
            ],
        ),
    ]
