# Generated by Django 3.0.6 on 2020-06-09 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skilltors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('upload_date', models.DateField(auto_now=True)),
                ('sale_type', models.CharField(choices=[('for sale', 'For Sale'), ('for free usage', 'For Free'), ('SOLD', 'For Sold')], default='for sale', max_length=50)),
                ('photo_main', models.ImageField(upload_to='%photos/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='%photos/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='%photos/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, upload_to='%photos/%Y/%m/%d')),
                ('photo_4', models.ImageField(blank=True, upload_to='%photos/%Y/%m/%d')),
                ('photo_5', models.ImageField(blank=True, upload_to='%photos/%Y/%m/%d')),
                ('photo_6', models.ImageField(blank=True, upload_to='%photos/%Y/%m/%d')),
                ('skilltors', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skilltors.Skilltor')),
            ],
        ),
    ]
